language: cpp
compiler: gcc

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            - ppa:beineri/opt-qt551
        packages:
            - qt55base
            - clang-3.7
            - g++-5
            - gcc-5

script: 
- qmake -r
- make check
